ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    map_frame: map

    odometry0: /odometry
    odometry0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]
    odometry0_queue_size: 10
    odometry0_differential: false
    odometry0_relative: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: true

    gps0: /gps/fix
    gps0_config: [true, true, false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    gps0_queue_size: 10
